/// Modèle d'une station radio DAB+ / Web.
class DabRadioStation {
  const DabRadioStation({
    required this.id,
    required this.name,
    required this.frequency,
    required this.streamUrl,
    required this.genre,
    this.logoEmoji = '📻',
  });

  final String id;
  final String name;
  final String frequency;
  final String streamUrl;
  final String genre;
  final String logoEmoji;
}

/// Liste complète des stations (Françaises et Internationales)
const kDabRadioStations = <DabRadioStation>[
  // ==========================================
  // STATIONS FRANÇAISES D'ORIGINE (8)
  // ==========================================
  DabRadioStation(
    id: 'france_inter',
    name: 'France Inter',
    frequency: 'DAB+ 5A',
    streamUrl: 'https://icecast.radiofrance.fr/franceinter-midfi.mp3',
    genre: 'Généraliste',
    logoEmoji: '🇫🇷',
  ),
  DabRadioStation(
    id: 'france_info',
    name: 'France Info',
    frequency: 'DAB+ 5A',
    streamUrl: 'https://icecast.radiofrance.fr/franceinfo-midfi.mp3',
    genre: 'Info',
    logoEmoji: '📰',
  ),
  DabRadioStation(
    id: 'fip',
    name: 'FIP',
    frequency: 'DAB+ 5A',
    streamUrl: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
    genre: 'Éclectique',
    logoEmoji: '🎷',
  ),
  DabRadioStation(
    id: 'france_musique',
    name: 'France Musique',
    frequency: 'DAB+ 5A',
    streamUrl: 'https://icecast.radiofrance.fr/francemusique-midfi.mp3',
    genre: 'Classique',
    logoEmoji: '🎻',
  ),
  DabRadioStation(
    id: 'rtl',
    name: 'RTL',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.radio.grouprtl.fr/rtl-1-48-128',
    genre: 'Généraliste',
    logoEmoji: '📡',
  ),
  DabRadioStation(
    id: 'europe1',
    name: 'Europe 1',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://stream.europe1.fr/europe1.mp3',
    genre: 'Info',
    logoEmoji: '🗞️',
  ),
  DabRadioStation(
    id: 'nrj',
    name: 'NRJ',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.nrjaudio.fm/oufdf5pmqu8uv',
    genre: 'Hits',
    logoEmoji: '🔥',
  ),
  DabRadioStation(
    id: 'rmc',
    name: 'RMC',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.radio.grouprtl.fr/rmc-1-48-128',
    genre: 'Talk',
    logoEmoji: '🎙️',
  ),

  // ==========================================
  // NOUVELLES STATIONS FRANÇAISES (30)
  // ==========================================
  DabRadioStation(
    id: 'radio_nova',
    name: 'Radio Nova',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://novazz.ice.infomaniak.ch/novazz-128.mp3',
    genre: 'Éclectique',
    logoEmoji: '✨',
  ),
  DabRadioStation(
    id: 'france_culture',
    name: 'France Culture',
    frequency: 'DAB+ 5A',
    streamUrl: 'https://icecast.radiofrance.fr/franceculture-midfi.mp3',
    genre: 'Culture',
    logoEmoji: '📚',
  ),
  DabRadioStation(
    id: 'france_bleu',
    name: 'France Bleu Paris',
    frequency: 'DAB+ 5B',
    streamUrl: 'https://icecast.radiofrance.fr/fb1071-midfi.mp3',
    genre: 'Généraliste',
    logoEmoji: '🇫🇷',
  ),
  DabRadioStation(
    id: 'mouv',
    name: 'Mouv\'',
    frequency: 'DAB+ 5B',
    streamUrl: 'https://icecast.radiofrance.fr/mouv-midfi.mp3',
    genre: 'Urbain',
    logoEmoji: '🎤',
  ),
  DabRadioStation(
    id: 'skyrock',
    name: 'Skyrock',
    frequency: 'DAB+ 7A',
    streamUrl: 'http://icecast.skyrock.net/s/natio_mp3_128k',
    genre: 'Urbain',
    logoEmoji: '🛹',
  ),
  DabRadioStation(
    id: 'fun_radio',
    name: 'Fun Radio',
    frequency: 'DAB+ 7A',
    streamUrl: 'https://streaming.radio.grouprtl.fr/fun-1-44-128',
    genre: 'Électro',
    logoEmoji: '🎧',
  ),
  DabRadioStation(
    id: 'europe_2',
    name: 'Europe 2',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://stream.europe2.fr/europe2.mp3',
    genre: 'Pop Rock',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'rfm',
    name: 'RFM',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://stream.rfm.fr/rfm.mp3',
    genre: 'Pop',
    logoEmoji: '🎵',
  ),
  DabRadioStation(
    id: 'cherie_fm',
    name: 'Chérie FM',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.nrjaudio.fm/mac6n8x9uu8uv',
    genre: 'Pop',
    logoEmoji: '❤️',
  ),
  DabRadioStation(
    id: 'nostalgie',
    name: 'Nostalgie',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.nrjaudio.fm/9k2h6m9vuu8uv',
    genre: 'Classiques',
    logoEmoji: '🕰️',
  ),
  DabRadioStation(
    id: 'rire_et_chansons',
    name: 'Rire & Chansons',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.nrjaudio.fm/s4k813g6uu8uv',
    genre: 'Humour',
    logoEmoji: '😂',
  ),
  DabRadioStation(
    id: 'tsf_jazz',
    name: 'TSF Jazz',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3',
    genre: 'Jazz',
    logoEmoji: '🎺',
  ),
  DabRadioStation(
    id: 'oui_fm',
    name: 'OUI FM',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://ouifm.ice.infomaniak.ch/ouifm-high.mp3',
    genre: 'Rock',
    logoEmoji: '🤘',
  ),
  DabRadioStation(
    id: 'radio_classique',
    name: 'Radio Classique',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3',
    genre: 'Classique',
    logoEmoji: '🎹',
  ),
  DabRadioStation(
    id: 'm_radio',
    name: 'M Radio',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://mradio.ice.infomaniak.ch/mradio-high.mp3',
    genre: 'Chanson Française',
    logoEmoji: '🐓',
  ),
  DabRadioStation(
    id: 'rtl2',
    name: 'RTL2',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://streaming.radio.grouprtl.fr/rtl2-1-44-128',
    genre: 'Pop Rock',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'bfm_business',
    name: 'BFM Business',
    frequency: 'DAB+ 7B',
    streamUrl: 'https://audio.bfmtv.com/bfmbusiness_128.mp3',
    genre: 'Éco/Info',
    logoEmoji: '📈',
  ),
  DabRadioStation(
    id: 'sud_radio',
    name: 'Sud Radio',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://start-sud.ice.infomaniak.ch/start-sud-high.mp3',
    genre: 'Talk',
    logoEmoji: '🗣️',
  ),
  DabRadioStation(
    id: 'radio_fg',
    name: 'Radio FG',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://radiofg.impek.com/fg.mp3',
    genre: 'Électro',
    logoEmoji: '🪩',
  ),
  DabRadioStation(
    id: 'latina',
    name: 'Latina',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://start-latina.ice.infomaniak.ch/start-latina-high.mp3',
    genre: 'Latino',
    logoEmoji: '💃',
  ),
  DabRadioStation(
    id: 'alouette',
    name: 'Alouette',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://alouette.ice.infomaniak.ch/alouette-high.mp3',
    genre: 'Hits',
    logoEmoji: '🐦',
  ),
  DabRadioStation(
    id: 'contact_fm',
    name: 'Contact FM',
    frequency: 'DAB+ 8A',
    streamUrl: 'https://contactfm.ice.infomaniak.ch/contactfm-high.mp3',
    genre: 'Hits',
    logoEmoji: '🐬',
  ),
  DabRadioStation(
    id: 'hit_west',
    name: 'Hit West',
    frequency: 'DAB+ 8B',
    streamUrl: 'https://hitwest.ice.infomaniak.ch/hitwest-high.mp3',
    genre: 'Hits',
    logoEmoji: '🌊',
  ),
  DabRadioStation(
    id: 'voltage',
    name: 'Voltage',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://start-voltage.ice.infomaniak.ch/start-voltage-high.mp3',
    genre: 'Hits',
    logoEmoji: '⚡',
  ),
  DabRadioStation(
    id: 'generations',
    name: 'Générations',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://generations.ice.infomaniak.ch/generations-high.mp3',
    genre: 'Urbain',
    logoEmoji: '🔥',
  ),
  DabRadioStation(
    id: 'jazz_radio',
    name: 'Jazz Radio',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3',
    genre: 'Jazz',
    logoEmoji: '🎷',
  ),
  DabRadioStation(
    id: 'beur_fm',
    name: 'Beur FM',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://beurfm.ice.infomaniak.ch/beurfm-high.mp3',
    genre: 'Généraliste',
    logoEmoji: '🌍',
  ),
  DabRadioStation(
    id: 'melody',
    name: 'Melody',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://melody.ice.infomaniak.ch/melody-high.mp3',
    genre: 'Variété',
    logoEmoji: '🎙️',
  ),
  DabRadioStation(
    id: 'radio_orient',
    name: 'Radio Orient',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://orient.ice.infomaniak.ch/orient-high.mp3',
    genre: 'Généraliste',
    logoEmoji: '🌴',
  ),
  DabRadioStation(
    id: 'chante_france',
    name: 'Chante France',
    frequency: 'DAB+ 9B',
    streamUrl: 'https://chantefrance.ice.infomaniak.ch/chantefrance-high.mp3',
    genre: 'Chanson Française',
    logoEmoji: '🥐',
  ),

  // ==========================================
  // STATIONS ÉTRANGÈRES (20)
  // ==========================================

  // Royaume-Uni (BBC)
  DabRadioStation(
    id: 'bbc_radio_1',
    name: 'BBC Radio 1',
    frequency: 'DAB+ UK 12B',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
    genre: 'Hits / Pop',
    logoEmoji: '🇬🇧',
  ),
  DabRadioStation(
    id: 'bbc_radio_2',
    name: 'BBC Radio 2',
    frequency: 'DAB+ UK 12B',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two',
    genre: 'Adult Contemporary',
    logoEmoji: '🇬🇧',
  ),
  DabRadioStation(
    id: 'bbc_radio_3',
    name: 'BBC Radio 3',
    frequency: 'DAB+ UK 12B',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three',
    genre: 'Classique / Culture',
    logoEmoji: '🇬🇧',
  ),
  DabRadioStation(
    id: 'bbc_radio_4',
    name: 'BBC Radio 4',
    frequency: 'DAB+ UK 12B',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm',
    genre: 'Talk / Info',
    logoEmoji: '🇬🇧',
  ),
  DabRadioStation(
    id: 'bbc_world',
    name: 'BBC World Service',
    frequency: 'DAB+ UK 12B',
    streamUrl: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service',
    genre: 'Info Internationale',
    logoEmoji: '🌍',
  ),

  // Belgique
  DabRadioStation(
    id: 'rtbf_la_premiere',
    name: 'La Première (RTBF)',
    frequency: 'DAB+ BE 11D',
    streamUrl: 'https://radios.rtbf.be/laprem-128.mp3',
    genre: 'Généraliste',
    logoEmoji: '🇧🇪',
  ),
  DabRadioStation(
    id: 'rtbf_classic_21',
    name: 'Classic 21',
    frequency: 'DAB+ BE 11D',
    streamUrl: 'https://radios.rtbf.be/classic21-128.mp3',
    genre: 'Classic Rock',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'vrt_stubru',
    name: 'Studio Brussel',
    frequency: 'DAB+ BE 11A',
    streamUrl: 'https://icecast.vrt.be/stubru-high.mp3',
    genre: 'Alternative',
    logoEmoji: '🇧🇪',
  ),

  // Espagne
  DabRadioStation(
    id: 'cadena_ser',
    name: 'Cadena SER',
    frequency: 'DAB+ ES 8A',
    streamUrl: 'https://25633.live.streamtheworld.com/CADENASER.mp3',
    genre: 'Généraliste / Info',
    logoEmoji: '🇪🇸',
  ),
  DabRadioStation(
    id: 'los40',
    name: 'LOS40',
    frequency: 'DAB+ ES 8A',
    streamUrl: 'https://20863.live.streamtheworld.com/LOS40.mp3',
    genre: 'Hits',
    logoEmoji: '🇪🇸',
  ),
  DabRadioStation(
    id: 'rne_radio_nacional',
    name: 'RNE Radio Nacional',
    frequency: 'DAB+ ES 8A',
    streamUrl: 'https://rtvelivestream.akamaized.net/rtvesec/rne/rne_main.m3u8',
    genre: 'Info / Culture',
    logoEmoji: '🇪🇸',
  ),

  // Italie
  DabRadioStation(
    id: 'rai_radio_1',
    name: 'Rai Radio 1',
    frequency: 'DAB+ IT 12C',
    streamUrl: 'https://icestreaming.rai.it/1.mp3',
    genre: 'Généraliste',
    logoEmoji: '🇮🇹',
  ),
  DabRadioStation(
    id: 'rtl_102_5',
    name: 'RTL 102.5 (IT)',
    frequency: 'DAB+ IT 12C',
    streamUrl: 'https://shoutcast.rtl.it/stream1',
    genre: 'Hits',
    logoEmoji: '🇮🇹',
  ),
  DabRadioStation(
    id: 'radio_italia',
    name: 'Radio Italia',
    frequency: 'DAB+ IT 12C',
    streamUrl: 'https://radioitaliasmi.akamaized.net/hls/live/2093118/RISMI/master.m3u8',
    genre: 'Musique Italienne',
    logoEmoji: '🇮🇹',
  ),

  // Canada
  DabRadioStation(
    id: 'ici_radio_canada',
    name: 'ICI Radio-Canada',
    frequency: 'Web / HD',
    streamUrl: 'https://rcavlive.akamaized.net/hls/live/2006635/P-2QMTL0_MTL/master.m3u8',
    genre: 'Généraliste',
    logoEmoji: '🇨🇦',
  ),
  DabRadioStation(
    id: 'cbc_radio_one',
    name: 'CBC Radio One',
    frequency: 'Web / HD',
    streamUrl: 'https://cbcliveradio-lh.akamaihd.net/i/CBCR1_TOR@118420/master.m3u8',
    genre: 'Talk / Info',
    logoEmoji: '🇨🇦',
  ),
  DabRadioStation(
    id: 'ckoi',
    name: 'CKOI 96.9',
    frequency: 'Web / FM',
    streamUrl: 'https://cogecomedia.leanstream.co/ckoifm-mp3',
    genre: 'Hits / Humour',
    logoEmoji: '⚜️',
  ),

  // États-Unis
  DabRadioStation(
    id: 'npr',
    name: 'NPR News',
    frequency: 'HD Radio US',
    streamUrl: 'https://npr-ice.streamguys1.com/live.mp3',
    genre: 'Info / Culture',
    logoEmoji: '🇺🇸',
  ),
  DabRadioStation(
    id: 'kexp',
    name: 'KEXP Seattle',
    frequency: 'HD Radio US',
    streamUrl: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
    genre: 'Indie / Alternative',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'wnyc',
    name: 'WNYC New York',
    frequency: 'HD Radio US',
    streamUrl: 'https://fm939.wnyc.org/wnycfm.aac',
    genre: 'Talk / Info',
    logoEmoji: '🗽',
  ),
  // ==========================================
  // AUTRES STATIONS FRANÇAISES
  // ==========================================
  DabRadioStation(
    id: 'france_musique_jazz',
    name: 'France Musique Jazz',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/francemusiquejazz-midfi.mp3',
    genre: 'Jazz',
    logoEmoji: '🎷',
  ),
  DabRadioStation(
    id: 'fip_electro',
    name: 'FIP Électro',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/fipelectro-midfi.mp3',
    genre: 'Électro',
    logoEmoji: '🎛️',
  ),
  DabRadioStation(
    id: 'fip_rock',
    name: 'FIP Rock',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/fiprock-midfi.mp3',
    genre: 'Rock',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'fip_jazz',
    name: 'FIP Jazz',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/fipjazz-midfi.mp3',
    genre: 'Jazz',
    logoEmoji: '🎷',
  ),
  DabRadioStation(
    id: 'fip_world',
    name: 'FIP Monde',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/fipworld-midfi.mp3',
    genre: 'Musique du Monde',
    logoEmoji: '🌍',
  ),
  DabRadioStation(
    id: 'fip_groove',
    name: 'FIP Groove',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/fipgroove-midfi.mp3',
    genre: 'Groove',
    logoEmoji: '🕺',
  ),
  DabRadioStation(
    id: 'mouv_rnb',
    name: 'Mouv\' R&B',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/mouvrnb-midfi.mp3',
    genre: 'R&B',
    logoEmoji: '🎤',
  ),
  DabRadioStation(
    id: 'mouv_rap_fr',
    name: 'Mouv\' Rap FR',
    frequency: 'Web',
    streamUrl: 'https://icecast.radiofrance.fr/mouvrapfr-midfi.mp3',
    genre: 'Rap',
    logoEmoji: '🇫🇷',
  ),
  DabRadioStation(
    id: 'nrj_hits',
    name: 'NRJ Hits',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nrj-hits',
    genre: 'Hits',
    logoEmoji: '🔥',
  ),
  DabRadioStation(
    id: 'nrj_dance',
    name: 'NRJ Dance',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nrj-dance',
    genre: 'Dance',
    logoEmoji: '💃',
  ),
  DabRadioStation(
    id: 'nrj_pop',
    name: 'NRJ Pop',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nrj-pop',
    genre: 'Pop',
    logoEmoji: '🎤',
  ),
  DabRadioStation(
    id: 'nostalgie_chansons_francaises',
    name: 'Nostalgie Chansons Françaises',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nostalgie-chansons-francaises',
    genre: 'Chanson Française',
    logoEmoji: '🇫🇷',
  ),
  DabRadioStation(
    id: 'nostalgie_disco',
    name: 'Nostalgie Disco',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nostalgie-disco-fever',
    genre: 'Disco',
    logoEmoji: '🪩',
  ),
  DabRadioStation(
    id: 'nostalgie_rock',
    name: 'Nostalgie Rock',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/nostalgie-rock',
    genre: 'Rock',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'cherie_fm_acoustic',
    name: 'Chérie FM Acoustic',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/cherie-fm-acoustic',
    genre: 'Acoustique',
    logoEmoji: '🎸',
  ),
  DabRadioStation(
    id: 'cherie_fm_love_songs',
    name: 'Chérie FM Love Songs',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/cherie-fm-love-songs',
    genre: 'Love Songs',
    logoEmoji: '❤️',
  ),
  DabRadioStation(
    id: 'rire_et_chansons_stand_up',
    name: 'Rire & Chansons Stand-Up',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/rire-et-chansons-stand-up',
    genre: 'Stand-Up',
    logoEmoji: '🎤',
  ),
  DabRadioStation(
    id: 'rire_et_chansons_canulars',
    name: 'Rire & Chansons Canulars',
    frequency: 'Web',
    streamUrl: 'https://streaming.nrjaudio.fm/rire-et-chansons-canulars',
    genre: 'Canulars',
    logoEmoji: '📞',
  ),
  DabRadioStation(
    id: 'rtl_100_francais',
    name: 'RTL 100% Français',
    frequency: 'Web',
    streamUrl: 'https://streaming.radio.grouprtl.fr/rtl-100-francais',
    genre: 'Chanson Française',
    logoEmoji: '🇫🇷',
  ),
  DabRadioStation(
    id: 'fun_radio_latino',
    name: 'Fun Radio Latino',
    frequency: 'Web',
    streamUrl: 'https://streaming.radio.grouprtl.fr/fun-latino',
    genre: 'Latino',
    logoEmoji: '💃',
  ),

  // ==========================================
  // AUTRES STATIONS INTERNATIONALES
  // ==========================================
  // Québec (Canada)
  DabRadioStation(
    id: 'ici_radio_canada_premiere',
    name: 'ICI Radio-Canada Première',
    frequency: 'Web',
    streamUrl: 'https://rcavlive.akamaized.net/hls/live/2006635/P-QcMt0_mtl/playlist.m3u8',
    genre: 'Info / Talk',
    logoEmoji: '🇨🇦',
  ),
  DabRadioStation(
    id: 'choi_radio_x',
    name: 'CHOI Radio X 98.1',
    frequency: 'FM 98.1',
    streamUrl: 'https://media.radiox.com/radiox',
    genre: 'Talk / Rock',
    logoEmoji: '🇨🇦',
  ),
  
  // Suisse
  DabRadioStation(
    id: 'rts_la_premiere',
    name: 'RTS La Première',
    frequency: 'DAB+ CH 12A',
    streamUrl: 'https://stream.srg-ssr.ch/m/la-1ere/mp3_128',
    genre: 'Généraliste',
    logoEmoji: '🇨🇭',
  ),
  DabRadioStation(
    id: 'couleur_3',
    name: 'Couleur 3',
    frequency: 'DAB+ CH 12A',
    streamUrl: 'https://stream.srg-ssr.ch/m/couleur3/mp3_128',
    genre: 'Alternative / Rock',
    logoEmoji: '🇨🇭',
  ),

  // Brésil
  DabRadioStation(
    id: 'jovem_pan_fm',
    name: 'Jovem Pan FM',
    frequency: 'FM 100.9',
    streamUrl: 'https://streaming29.radionomy.com/Radionomy_Jovem_Pan', // Placeholder, needs robust URL
    genre: 'Hits / Talk',
    logoEmoji: '🇧🇷',
  ),
  DabRadioStation(
    id: 'radio_globo',
    name: 'Rádio Globo',
    frequency: 'FM 98.1',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/RADIO_GLOBO.mp3', // Placeholder
    genre: 'Généraliste / Info',
    logoEmoji: '🇧🇷',
  ),

  // Allemagne
  DabRadioStation(
    id: '1live',
    name: '1LIVE',
    frequency: 'DAB+ DE 11D',
    streamUrl: 'https://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3',
    genre: 'Hits / Pop',
    logoEmoji: '🇩🇪',
  ),
  DabRadioStation(
    id: 'ndr_2',
    name: 'NDR 2',
    frequency: 'DAB+ DE 11B',
    streamUrl: 'https://ndr-ndr2-niedersachsen.icecast.ndr.de/ndr/ndr2/niedersachsen/mp3/128/stream.mp3',
    genre: 'Pop / Adult Contemporary',
    logoEmoji: '🇩🇪',
  ),

  // Irlande
  DabRadioStation(
    id: 'rte_radio_1',
    name: 'RTÉ Radio 1',
    frequency: 'FM 88-90',
    streamUrl: 'https://listen.rte.ie/rte-radio-1', // Generic URL
    genre: 'Talk / News / Music',
    logoEmoji: '🇮🇪',
  ),
  DabRadioStation(
    id: 'today_fm',
    name: 'Today FM',
    frequency: 'FM 100-102',
    streamUrl: 'https://edge.audioxi.com/TW',
    genre: 'Pop / Rock / Talk',
    logoEmoji: '🇮🇪',
  ),

  // Maroc
  DabRadioStation(
    id: 'hit_radio',
    name: 'Hit Radio',
    frequency: 'FM 99.8',
    streamUrl: 'https://hitradio-maroc.ice.infomaniak.ch/hitradio-maroc-128.mp3',
    genre: 'Hits',
    logoEmoji: '🇲🇦',
  ),
  DabRadioStation(
    id: 'radio_2m',
    name: 'Radio 2M',
    frequency: 'FM 93.1',
    streamUrl: 'https://radio2m.ice.infomaniak.ch/radio2m-128.mp3',
    genre: 'Info / Musique',
    logoEmoji: '🇲🇦',
  ),

  // Japon
  DabRadioStation(
    id: 'tbs_radio',
    name: 'TBS Radio',
    frequency: 'AM 954 / FM 90.5',
    streamUrl: 'https://radiko.jp/v2/api/stream.mp3', // Placeholder, Radiko is complex
    genre: 'Talk / News',
    logoEmoji: '🇯🇵',
  ),
  DabRadioStation(
    id: 'tokyo_fm',
    name: 'Tokyo FM',
    frequency: 'FM 80.0',
    streamUrl: 'https://radiko.jp/v2/api/stream.mp3', // Placeholder
    genre: 'Pop',
    logoEmoji: '🇯🇵',
  ),

  // Corée du Sud
  DabRadioStation(
    id: 'kbs_cool_fm',
    name: 'KBS Cool FM',
    frequency: 'FM 89.1',
    streamUrl: 'https://servertier3.kbs.co.kr/live', // Placeholder
    genre: 'K-Pop / Hits',
    logoEmoji: '🇰🇷',
  ),
  DabRadioStation(
    id: 'mbc_fm4u',
    name: 'MBC FM4U',
    frequency: 'FM 91.9',
    streamUrl: 'https://listen.imbc.com/fm4u', // Placeholder
    genre: 'Pop / Talk',
    logoEmoji: '🇰🇷',
  ),

  // Australie
  DabRadioStation(
    id: 'triple_j',
    name: 'triple j',
    frequency: 'FM 105.7',
    streamUrl: 'https://live-radio01.mediahubaustralia.com/2TJW/mp3/',
    genre: 'Alternative / Indie',
    logoEmoji: '🇦🇺',
  ),
  DabRadioStation(
    id: 'abc_radio_sydney',
    name: 'ABC Radio Sydney',
    frequency: 'AM 702',
    streamUrl: 'https://live-radio01.mediahubaustralia.com/2LRW/mp3/',
    genre: 'Talk / News',
    logoEmoji: '🇦🇺',
  ),
];
